### ISSUE TITLE
Requested value 'SECTION' was not found.

### ISSUE THREAD

**Issue by stuurge** [cdmvision/unity-figma-importer#81]
On importing assets from Figma into Unity using the Figma Downloader, both the branch refresh and Download button yields a 
Newtonsoft.Json.JsonSerializationException: Error converting value "SECTION" to type 'Cdm.Figma.NodeType' exception.
Here is the full print out:
```
UnityEngine.Debug:LogError (object)
Cdm.Figma.Editor.FigmaDownloaderAssetEditor/<DownloadFilesAsync>d__26:MoveNext () (at ./Library/PackageCache/com.cdm.figma@fca65130ed/Editor/FigmaDownloaderAssetEditor.cs:248)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:SetException (System.Exception)
Cdm.Figma.Editor.FigmaDownloaderAssetEditor/<DownloadAndSaveFigmaFileAsync>d__30:MoveNext () (at ./Library/PackageCache/com.cdm.figma@fca65130ed/Editor/FigmaDownloaderAssetEditor.cs:366)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Cdm.Figma.FigmaFile>:SetException (System.Exception)
Cdm.Figma.FigmaDownloader/<DownloadFileAsync>d__10:MoveNext () (at ./Library/PackageCache/com.cdm.figma@fca65130ed/Runtime/FigmaDownloader.cs:42)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Cdm.Figma.FigmaFile>:SetException (System.Exception)
Cdm.Figma.FigmaDownloader/<DownloadFileAsyncInternal>d__11:MoveNext () (at ./Library/PackageCache/com.cdm.figma@fca65130ed/Runtime/FigmaDownloader.cs:106)
UnityEngine.UnitySynchronizationContext:ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```
I see that #72 has a similar issue, which was fixed on an update. Is this happening for anyone currently using this tool, or is it an oversight on my part?

**Comment by ibrahimpenekli** [comment]
Hi @stuurge,

It looks like Section node is new to Figma Design or we missed it. 
I fixed the issue but Section node type is not supported (is not imported in Unity)
In the next version you will be able to download and import your file without any error.
As workaround, you can remove the section nodes from your Figma design.

Thanks for the report!
