### ISSUE TITLE
Unity UI Toolkit

### ISSUE THREAD

**Issue by ZoedAb** [cdmvision/unity-figma-importer#83]
how can i use it with Unity UI Toolkit the package uses Simple Unity.UI elements and there is no documents on how can i add the design to UI Builder

**Comment by gunseliozkan** [comment]
The package does not support UI Toolkit yet. 
Here is the documentation link: [Unity Figma Importer Documentation](https://cdmdocs.gitbook.io/unity-figma-importer)

**Comment by J-Laureijs** [comment]
Are there any plans to support the UI Toolkit? Or is it not planned for now?

**Comment by gunseliozkan** [comment]
We initially had a plan to support UI Toolkit when it is more stable. We do not have any timeline now, bu it is on the agenda. @J-Laureijs
